---
- name: Ensure /srv/uptimekuma directory exists
  file:
    path: /srv/uptimekuma
    state: directory

- name: Create compose.yml file
  copy:
    dest: /srv/uptimekuma/compose.yml
    content: |
      services:
        uptime-kuma:
          image: louislam/uptime-kuma:1
          volumes:
            - ./data:/app/data
          ports:
            - 3001:3001
          restart: always